version: '3.3'
services:
  dev:
    container_name: micronet-auth-apis
    image: micronet-auth-apis-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 4000:4000
      - 3001:9229
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
networks:
    nesjs-network:
      driver: bridge
